### ISSUE TITLE
custom FEN position ?

### ISSUE THREAD

**Issue by tissatussa** [JacquesRW/perft#3]
i assume this little utility is for your own development only ? It seems the program just has 5 fixed FENs to process .. are arguments accepted, eg. a custom FEN ?  Or should the source be modified for that and recompile ?

**Comment by JacquesRW** [comment]
From the README
```
A fast perft implementation, mostly a testing repo for akimbo.
```
Arguments are not accepted because I just run those 5 positions every time to check I haven't broken anything.


If you want to put your own FEN strings in, just edit the following, at `line 14`, in `main.rs`
```rust
const POSITIONS: [(&str, u8, u64); 5] = [
    ("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1", 6, 119_060_324),
    ("r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1", 5, 193_690_690,),
    ("8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - -", 7, 178_633_661),
    ("rnbq1k1r/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQK2R w KQ - 1 8", 5, 89_941_194),
    ("r4rk1/1pp1qppp/p1np1n2/2b1p1B1/2B1P1b1/P1NP1N2/1PP1QPPP/R4RK1 w - - 0 10", 5, 164_075_551),
];
```
where the tuple is `(fen string, depth to do perft to, expected number of nodes)`.
If you give an incorrect expected number of nodes, it will fail an assert and show what it should be.

There is no FEN verification so if you give an incorrect FEN string it'll probably just panic and exit.

Remember to compile in release mode.

**Comment by tissatussa** [comment]
Thanks for this quick and clear answer. This is what i was thinking .. so the program is simple but easily adjustable.

**Comment by tissatussa** [comment]
Thanks for this utility.
